name: laptop2

x-global_env: &global_env
  FABRIC_CA_HOME: /etc/hyperledger/fabric-ca-server
  FABRIC_CA_SERVER_TLS_ENABLED: true

services:
  ca_org3:
    image: hyperledger/fabric-ca:${CA_VERSION}
    container_name: ca_org3
    network_mode: "host"
    environment:
      <<: *global_env
      FABRIC_CA_SERVER_CA_NAME: ca-org3
      FABRIC_CA_SERVER_PORT: ${ORG3_CA_PORT}
      FABRIC_CA_SERVER_CSR_HOSTS: localhost,ca.org3.example.com,${LAPTOP2_IP}
      FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS: "0.0.0.0:${ORG3_CA_OPERATION_PORT}"
    volumes:
      - ../organizations/fabric-ca/org3/ca:/etc/hyperledger/fabric-ca-server
    command: sh -c "fabric-ca-server start -b admin:adminpw -d"

  tlsca_org3:
    image: hyperledger/fabric-ca:${CA_VERSION}
    container_name: tlsca_org3
    network_mode: "host"
    environment:
      <<: *global_env
      FABRIC_CA_SERVER_CA_NAME: tlsca-org3
      FABRIC_CA_SERVER_PORT: ${ORG3_TLSCA_PORT}
      FABRIC_CA_SERVER_CSR_HOSTS: localhost,tlsca.org3.example.com,${LAPTOP2_IP}
      FABRIC_CA_SERVER_OPERATIONS_LISTENADDRESS: "0.0.0.0:${ORG3_TLSCA_OPERATION_PORT}"
    volumes:
      - ../organizations/fabric-ca/org3/tlsca:/etc/hyperledger/fabric-ca-server
    command: sh -c "fabric-ca-server start -b admin:adminpw -d"
