name: laptop2
networks:
  fabric:
    name: fabric

services:
  ca_org3:
    image: hyperledger/fabric-ca:${CA_VERSION}
    container_name: ca.org3.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=${ORG3_CA_PORT}
      - FABRIC_CA_SERVER_CSR_HOSTS=localhost,ca.org3.example.com,${LAPTOP2_IP}
    ports:
      - "${ORG3_CA_PORT}:${ORG3_CA_PORT}"
    volumes:
      - ../organizations/fabric-ca/org3/ca:/etc/hyperledger/fabric-ca-server
    command: sh -c "fabric-ca-server start -b admin:adminpw -d"
    networks: [fabric]

  tlsca_org3:
    image: hyperledger/fabric-ca:${CA_VERSION}
    container_name: tlsca.org3.example.com
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=tlsca-org3
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_PORT=${ORG3_TLSCA_PORT}
      - FABRIC_CA_SERVER_CSR_HOSTS=localhost,tlsca.org3.example.com,${LAPTOP2_IP}
    ports:
      - "${ORG3_TLSCA_PORT}:${ORG3_TLSCA_PORT}"
    volumes:
      - ../organizations/fabric-ca/org3/tlsca:/etc/hyperledger/fabric-ca-server
    command: sh -c "fabric-ca-server start -b admin:adminpw -d"
    networks: [fabric]