name: laptop2
networks:
  fabric:
    name: fabric

volumes:
  ordererdata:
  peer0org2:
  peer0org3:

services:
  orderer.example.com:
    image: hyperledger/fabric-orderer:${FABRIC_VERSION}
    container_name: orderer.example.com
    environment:
      - FABRIC_LOGGING_SPEC=INFO
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_LISTENPORT=${ORDERER_PORT}
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/var/hyperledger/orderer/msp

      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

      - ORDERER_CHANNELPARTICIPATION_ENABLED=true
      - ORDERER_GENERAL_BOOTSTRAPMETHOD=none

      - ORDERER_ADMIN_LISTENADDRESS=0.0.0.0:${ORDERER_ADMIN_PORT}
      - ORDERER_ADMIN_TLS_ENABLED=true
      - ORDERER_ADMIN_TLS_CERTIFICATE=/var/hyperledger/orderer/tls/server.crt
      - ORDERER_ADMIN_TLS_PRIVATEKEY=/var/hyperledger/orderer/tls/server.key
      - ORDERER_ADMIN_TLS_ROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]
      - ORDERER_ADMIN_TLS_CLIENTAUTHREQUIRED=true
      - ORDERER_ADMIN_TLS_CLIENTROOTCAS=[/var/hyperledger/orderer/tls/ca.crt]

      - ORDERER_OPERATIONS_LISTENADDRESS=0.0.0.0:9444
    ports:
      - "${ORDERER_PORT}:${ORDERER_PORT}"
      - "${ORDERER_ADMIN_PORT}:${ORDERER_ADMIN_PORT}"
      - "9444:9444"
    volumes:
      - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/msp:/var/hyperledger/orderer/msp
      - ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls:/var/hyperledger/orderer/tls
      - ordererdata:/var/hyperledger/production/orderer
    extra_hosts:
      - "peer0.org1.example.com:${LAPTOP1_IP}"
      - "peer0.org2.example.com:${LAPTOP2_IP}"
      - "peer0.org3.example.com:${LAPTOP2_IP}"
    networks: [fabric]